### ISSUE TITLE
[vite:css] Cannot read properties of null (reading 'moduleGraph')

### ISSUE THREAD

**Issue by thomasvt1** [nonzzz/vite-plugin-stylex#19]
After upgrade from 0.4.1 to 0.5.0/0.5.1 the `vite build` command now fails

I added `manuallyControlCssOrder: true` to vite config, that fixes the build (but breaks styling)

Error:
```
x Build failed in 290ms
error during build:
TypeError: [vite:css] Cannot read properties of null (reading 'moduleGraph')
file: vite-plugin:stylex.css
    at file:///Users/thomasvt/Developer/Workspace/adv-decision-support-fe/node_modules/vite-plugin-stylex-dev/dist/index.mjs:2:2377
    at a.transform (file:///Users/thomasvt/Developer/Workspace/adv-decision-support-fe/node_modules/vite-plugin-stylex-dev/dist/index.mjs:2:780)
    at async transform (file:///Users/thomasvt/Developer/Workspace/adv-decision-support-fe/node_modules/rollup/dist/es/shared/node-entry.js:18513:16)
    at async ModuleLoader.addModuleSource (file:///Users/thomasvt/Developer/Workspace/adv-decision-support-fe/node_modules/rollup/dist/es/shared/node-entry.js:18729:36)
```

**Comment by nonzzz** [comment]
Minimum reproduction please

**Comment by thomasvt1** [comment]
@nonzzz here you go -> https://stackblitz.com/~/github.com/thomasvt1/vitejs-vite-5twphh

If you run `npm run build` it will return the error

Whilst creating the reproduction I noticed that it happens when passing the '--mode' in vite

**Comment by nonzzz** [comment]
[vite-env](https://vitejs.dev/guide/env-and-mode.html#node-env-and-modes). I'll synchronize it with the `isProduction` logic of vite itself.

**Comment by nonzzz** [comment]
By the way, option `manuallyControlCssOrder` is generally not used.

**Comment by nonzzz** [comment]
`v0.5.2` has been released.
